# Generated by Django 2.1 on 2018-08-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registed_dt', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=10)),
                ('faceBook', models.CharField(max_length=50, null=True)),
                ('youtube', models.CharField(max_length=50, null=True)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.ArtistInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceBookId', models.CharField(max_length=10, null=True)),
                ('kakaoTalkId', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=10)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('memberType', models.CharField(default='U', max_length=10)),
                ('deviceToken', models.CharField(max_length=30)),
                ('registed_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registed_dt', models.DateTimeField(auto_now_add=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('location', models.CharField(max_length=10)),
                ('lat', models.IntegerField()),
                ('lot', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.Genre')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.ArtistInfo')),
            ],
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.Member'),
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.Member'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='genreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.Genre'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.ArtistInfo'),
        ),
    ]
