# Generated by Django 2.1 on 2018-08-21 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.ArtistInfo')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiplace.Member')),
            ],
        ),
        migrations.RenameField(
            model_name='artistgenre',
            old_name='memberId',
            new_name='artistId',
        ),
    ]
