# Generated by Django 2.1 on 2018-08-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0002_auto_20180821_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinfo',
            name='name',
            field=models.CharField(default='artist', max_length=20),
        ),
    ]
