# Generated by Django 2.1 on 2018-08-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0003_artistinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
