# Generated by Django 2.1 on 2018-08-23 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0004_auto_20180821_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='indiplace.Member'),
        ),
    ]
