# Generated by Django 2.1 on 2018-08-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0005_auto_20180823_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_info', to='indiplace.Member'),
        ),
    ]
