# Generated by Django 2.1 on 2018-08-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0006_auto_20180823_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistinfo',
            old_name='location',
            new_name='artistLocation',
        ),
    ]
