# Generated by Django 2.1 on 2018-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0008_auto_20180823_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistgenre',
            name='artistId',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='genreId',
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='genre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistinfo',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performance',
            name='genre',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ArtistGenre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
