# Generated by Django 2.1 on 2018-08-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0009_auto_20180825_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='memberId',
            new_name='artistId',
        ),
    ]
