# Generated by Django 2.1 on 2018-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0010_auto_20180825_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinfo',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
