# Generated by Django 2.1 on 2018-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0012_auto_20180827_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
