# Generated by Django 2.1 on 2018-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0013_auto_20180827_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='genre',
        ),
        migrations.AddField(
            model_name='performance',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
