# Generated by Django 2.1 on 2018-08-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0015_auto_20180830_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='deviceToken',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='faceBookId',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kakaoTalkId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
