# Generated by Django 2.1 on 2018-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0016_auto_20180831_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='genre',
            field=models.IntegerField(default=1),
        ),
    ]
