# Generated by Django 2.1 on 2018-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0017_performance_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='genre',
            field=models.IntegerField(),
        ),
    ]
