# Generated by Django 2.1 on 2018-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0018_auto_20180831_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='faceBookId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='kakaoTalkId',
            field=models.IntegerField(blank=True),
        ),
    ]
