# Generated by Django 2.1 on 2018-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0019_auto_20180831_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='kakaoTalkId',
            field=models.IntegerField(null=True),
        ),
    ]
