# Generated by Django 2.1 on 2018-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0020_auto_20180831_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='lot',
            field=models.FloatField(),
        ),
    ]
