# Generated by Django 2.1 on 2018-09-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0021_auto_20180831_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='kakaoTalkId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
