# Generated by Django 2.1 on 2018-09-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiplace', '0022_auto_20180906_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='kakaoTalkId',
            field=models.IntegerField(null=True),
        ),
    ]
